package com.webmanager.enums;

public enum EmployeeRole {
    DEVELOPER,
    QA_ENGINEER,
    DEVOPS_ENGINEER,
    TECH_LEAD,
    SOFTWARE_ARCHITECT,
    PRODUCT_OWNER,
    PRODUCT_MANAGER,
    PROJECT_MANAGER,
    SCRUM_MASTER,
    UX_UI_DESIGNER,
    DATA_ENGINEER,
    DATA_SCIENTIST,
    DBA,
    SUPPORT_ANALYST,
    BUSINESS_ANALYST,
    SECURITY_ENGINEER,
    SRE,
    TECHNICAL_WRITER,
    HR_ANALYST,
    ENGINEERING_MANAGER,
    CTO
}